from device_descriptor import (
    ControlDescriptor,
    ControlType,
    DeviceDescriptor,
    ReportFormat,
)


def default_descriptor() -> DeviceDescriptor:
    controls = [
        ControlDescriptor(
            1,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=0,
            bit_width=1,
            label="Button 1",
        ),
        ControlDescriptor(
            2,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=1,
            bit_width=1,
            label="Button 2",
        ),
        ControlDescriptor(
            3,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=2,
            bit_width=1,
            label="Button 3",
        ),
        ControlDescriptor(
            4,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=3,
            bit_width=1,
            label="Button 4",
        ),
        ControlDescriptor(
            5,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=4,
            bit_width=1,
            label="Button 5",
        ),
        ControlDescriptor(
            6,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=5,
            bit_width=1,
            label="Button 6",
        ),
        ControlDescriptor(
            7,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=6,
            bit_width=1,
            label="Button 7",
        ),
        ControlDescriptor(
            8,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=7,
            bit_width=1,
            label="Button 8",
        ),
        ControlDescriptor(
            9,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=8,
            bit_width=1,
            label="Joy Left",
        ),
        ControlDescriptor(
            10,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=9,
            bit_width=1,
            label="Joy Right",
        ),
        ControlDescriptor(
            11,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=10,
            bit_width=1,
            label="Joy Up",
        ),
        ControlDescriptor(
            12,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=11,
            bit_width=1,
            label="Joy Down",
        ),
        ControlDescriptor(
            13,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=12,
            bit_width=1,
            label="Select",
        ),
        ControlDescriptor(
            14,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=13,
            bit_width=1,
            label="Start",
        ),
        ControlDescriptor(
            15,
            ControlType.BUTTON,
            ReportFormat.BITFIELD,
            bit_index=14,
            bit_width=1,
            label="Pair",
        ),
    ]

    return DeviceDescriptor(
        protocol_version=1,
        report_format=ReportFormat.BITFIELD,
        report_bytes=4,
        control_count=len(controls),
        controls=controls,
    )
